# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, commit-msg, pre-push]
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.26
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix, --ignore, FIX002]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.4
    hooks:
      - id: commitizen

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
    - id: pytest-check
      types: [python]
      name: pytest-check
      entry: uv run pytest --no-cov
      language: system
      pass_filenames: false
      always_run: true
      stages: [pre-push, manual]
