#!/usr/bin/python
HTTP_ = 'http://'
HTTPS_ = 'https://'

PUBLISH_MULTIPLE_URL = '/observation/multiple'
PUBLISH_PREDICTION_MULTIPLE_URL = '/prediction/multiple'
GET_OBSERVATIONS_URL = '/observation'
GET_LAST_VALUE_URL = '/observation/lastvalue'
GET_PREDICTIONS_URL = '/prediction'
PUBLISH_SINGLE_URL = '/observation/single'
PUBLISH_PREDICTION_SINGLE_URL = '/prediction/single'
PUBLISH_RECORD_URL = '/observation/record'
PUBLISH_PLAIN_CSV_URL = '/observation/csv/nofile'
FOI_URL = '/featureofinterest'
LOGIN_DEVICE_URL = '/login/device'
LOGIN_USER_URL = '/login/'
SOCKET_URL = '/socket'
SERIES_URL = '/series/'
ACTIONS_URL = '/newaction/'
DEVICE_ALERT_URL = '/alerts/device/send'
DEVICE_METADATA_URL = '/featureofinterest/metadata'
PUBLISH_INFRASTRUCTURE = '/featuretag'
PUBLISH_INFRASTRUCTURE_METADATA = '/featuretag/withmetadata'
PUBLISH_INFRASTRUCTURE_SIMPLE = '/featuretag/simple'
FILE = 'Configuration.properties'
